name: ci
on:
  push:
    paths:
      - '**.lua'
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '.gitmodules'
      - '.gitignore'
      - '.gitattributes'
      - 'conanfile.txt'
      - 'deps/**'
      - 'src/**'
      - 'utils/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.lua'
      - '**.cpp'
      - '**.c'
      - '**.hpp'
      - '**.h'
      - '.gitmodules'
      - '.gitignore'
      - '.gitattributes'
      - 'conanfile.txt'
      - 'deps/**'
      - 'src/**'
      - 'utils/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "conan>=2,<3" requests
          conan profile detect --force
      - name: Configure MSBuild environment
        uses: microsoft/setup-msbuild@v2
      - name: build
        run: |
          ./generate.bat
          cd build
          msbuild ImasSCSP-localify.sln -m -p:Configuration=Release
      - name: prepare-package
        run: |
          mkdir package
          cp build/bin/x64/Release/version.dll package/version.dll
          cp resources/scsp-config.json package/scsp-config.json
          cp -r resources/schinese/scsp_localify package/scsp_localify
      - uses: actions/upload-artifact@v4
        with:
          name: scsp-localify
          path: package
      - uses: actions/upload-artifact@v4
        with:
          name: scsp-localify-dll
          path: package/version.dll